port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
mode: Rule
log-level: info
external-controller: ':9990'
clash-for-android:
    append-system-dns: false
hosts:
    mtalk.google.com: 108.177.125.188
    tagss.pro: 104.26.4.238
dns:
    enable: true
    prefer-h3: true
    listen: '127.0.0.1:5334'
    default-nameserver: [180.184.1.1, 119.29.29.29, 223.5.5.5]
    enhanced-mode: fake-ip
    fake-ip-range: 198.18.0.1/16
    use-hosts: true
    nameserver-policy: { 'geosite:cn,apple,category-games@cn,private': [119.29.29.29, 180.184.1.1, 223.5.5.5] }
    nameserver: ['https://223.5.5.5/dns-query', 'https://223.6.6.6/dns-query', 'https://120.53.53.53/dns-query']
    fallback: ['https://101.101.101.101/dns-query', 'https://208.67.220.220/dns-query', 'https://114514.dns.nextdns.io/dns-query#h3=true']
    proxy-server-nameserver: ['https://doh.pub/dns-query', 'https://dns.alidns.com/dns-query']
    fallback-filter: { geoip: true, ipcidr: [240.0.0.0/4, 0.0.0.0/32, 223.75.236.241/32, 182.43.124.6/32, 106.74.25.198/32, 183.192.65.101/32], domain: [+.google.cn, +.tagss01.pro, +.tagss02.pro, +.tagss03.pro, +.tagss04.pro, +.tagss05.pro, +.tagcdnsub.work, +.jsdelivr.net, +.proton.me] }