port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
allow-lan: true
mode: Rule
log-level: info
external-controller: ':9990'
dns:
  enabled: true
  nameserver:
    - 114.114.114.114
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 8.8.4.4
    - tls://1.0.0.1:853
    - tls://dns.google:853
script:
    shortcuts:
        quic: network == 'udp' and dst_port == 443